import Head from 'next/head';
import Layout from '@component/components/layout/Layout';
import './_app.css';

export default function App({ Component, pageProps }) {
  return (
    <Layout>
      <Head>
        <title>Get that ref?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Layout>
  );
}
