import { useState } from 'react';
import Head from 'next/head';
import './_app.css';

import Header from '../components/layout/Header';
import Marquee from '../components/ui/Marquee';
import { SearchProvider } from '../context/SearchContext';
import { Container } from '@mui/material';
import { client } from '../apollo';
import { ApolloProvider } from '@apollo/client';
import Link from 'next/link';
import StarIcon from '@mui/icons-material/Star';

import useAuth from './../hooks/auth-hook';
import AuthContext from './../context/auth-context';
import AppModal from '../components/ui/Modal';
import AuthForms from '../components/layout/AuthForms';

export default function App({ Component, pageProps }) {
  const { token, login, logout, userType } = useAuth();
  console.log('token', token);

  const [isModalOpen, setIsModalOpen] = useState(false);

  const toggleModal = () => {
    setIsModalOpen(!isModalOpen); // Toggle the modal state
  };

  return (
    <>
      <Head>
        <title>Got that ref?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Marquee>
        YOU'VE SEEN A{' '}
        <em style={{ color: '#ff9799', fontStyle: 'normal' }}>
          VISUAL ARTS REFERENCE
        </em>{' '}
        IN A MOVIE OR SERIES?{' '}
        <Link
          style={{ color: '#fff', textDecoration: 'none' }}
          href="/send-a-reference"
        >
          <StarIcon sx={{ marginX: '5px' }} />
          SUBMIT A
          <em style={{ color: '#ff69de', fontStyle: 'normal' }}>
            &nbsp;NEW REFERENCE HERE
          </em>
          <StarIcon sx={{ marginX: '5px' }} />
        </Link>
      </Marquee>

      <AuthContext.Provider
        value={{
          isLoggedIn: !!token,
          token: token,
          userType: userType,
          login,
          logout,
        }}
      >
        <SearchProvider>
          <Header toggleModal={toggleModal} />

          <ApolloProvider client={client}>
            <AppModal open={isModalOpen} handleClose={toggleModal}>
              <AuthForms onSuccessfulSubmit={toggleModal} />
            </AppModal>

            <Container maxWidth="xlg" style={{ background: '#efeffd' }}>
              <main style={{ padding: '30px 0' }}>
                <Component {...pageProps} />
              </main>
            </Container>
          </ApolloProvider>
        </SearchProvider>
      </AuthContext.Provider>
    </>
  );
}
